"""Add room_no to User

Revision ID: 3ae5dc679601
Revises: 49fef594fff0
Create Date: 2026-07-02 08:31:54.112279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ae5dc679601'
down_revision: Union[str, Sequence[str], None] = '49fef594fff0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('room_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'room_no')
    # ### end Alembic commands ###
