"""update extras booking

Revision ID: 49fef594fff0
Revises: 5431c4b69dad
Create Date: 2026-07-02 06:36:32.875579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49fef594fff0'
down_revision: Union[str, Sequence[str], None] = '5431c4b69dad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE bookingstatus ADD VALUE IF NOT EXISTS 'missed'")
    op.execute("ALTER TYPE bookingstatus ADD VALUE IF NOT EXISTS 'cancelled'")
    op.execute("ALTER TYPE bookingstatus ADD VALUE IF NOT EXISTS 'cancel_requested'")
    
    op.add_column('extras_items', sa.Column('date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False))
    op.execute("DO $$ BEGIN CREATE TYPE mealtype AS ENUM ('breakfast', 'lunch', 'dinner'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("ALTER TABLE extras_items ADD COLUMN meal_type mealtype DEFAULT 'lunch'::mealtype NOT NULL")
    op.alter_column('extras_items', 'opens_at',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="CURRENT_DATE + opens_at")
    op.alter_column('extras_items', 'closes_at',
               existing_type=postgresql.TIME(),
               type_=sa.DateTime(),
               existing_nullable=False,
               postgresql_using="CURRENT_DATE + closes_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('extras_items', 'closes_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('extras_items', 'opens_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.drop_column('extras_items', 'meal_type')
    op.drop_column('extras_items', 'date')
    # ### end Alembic commands ###
